server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://kaloquan:123456@peer2:8762/eureka
  instance:
    hostname: peer1
spring:
  application:
    name: cinema-eureka
security:
  user:
    name: kaloquan
    password: 123456