server:
  port: 8000
spring:
  application:
    name: cinema-user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
eureka:
  client:
    service-url:
      defaultZone: http://kaloquan:123456@peer1:8761/eureka,http://kaloquan:123456@peer2:8762/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      name: cinema-user
      version: 1.0
      description: user center
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@